import {ControllerPlayer} from './controller-player.js';
const data=window.RELEASE_DESK_DATA,$=id=>document.getElementById(id);
const escape=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const counts=data.coverage.counts,lessons=data.lessons.filter(l=>l.available),actions=new Map(data.bindings.actions.map(a=>[a.name,a]));
const titles={'equipment-picker-open-release':'Open your equipment','commands-held-open-release':'Give a buddy command','vr-binocular-latch-enter':'Equip binoculars','vr-binocular-latch-stow':'Put binoculars away','pause-open':'Open Pause','pause-close':'Return to the field','standing-to-crouched':'Crouch','crouched-to-prone':'Go prone','prone-to-crouched':'Rise to a crouch','crouched-to-standing':'Stand up'};
const descriptions={'equipment-picker-open-release':'Hold {control} to reveal the equipment picker. Release to return to normal controls.','commands-held-open-release':'Hold {control} to show the command choices. Release to leave the command view.','vr-binocular-latch-enter':'Hold {control} together to equip binoculars.','vr-binocular-latch-stow':'Press {control} in binocular mode to put them away.','pause-open':'Hold {control} to open Pause. Inspect the separate final-eye review before accepting its fit.','pause-close':'Press {control} to return from Pause.','standing-to-crouched':'Tap {control} while standing to crouch.','crouched-to-prone':'Hold {control} while crouched to go prone.','prone-to-crouched':'Tap {control} while prone to rise into a crouch.','crouched-to-standing':'Tap {control} while crouched to stand.'};
const tabs=[['overview','Release plan'],['report','55 issues'],['historical_feature','Features'],['control_action','Controls'],['situation','Situations'],['equipment','Equipment'],['settings','Settings'],['numbers','Numeric audit']];
let activeTab='overview',activeLesson=null,player=null,playing=false,frameLoop=0;
const video=$('game-video');
const actionName=row=>row.id.startsWith('ACTION.')?row.id.slice(7):row.id;
$('counts').innerHTML=[[counts.report,'reports to resolve'],[counts.historical_feature,'recovered feature families'],[counts.control_action,'effective actions'],[lessons.length,'recorded action lessons'],[0,'reports fully accepted']].map(([n,label])=>`<span><b>${n}</b>${label}</span>`).join('');
$('plan').innerHTML=data.plan.map(([n,title,body])=>`<article><b>${n}</b><strong>${escape(title)}</strong><p>${escape(body)}</p></article>`).join('');
$('tabs').innerHTML=tabs.map(([id,label])=>`<button data-tab="${id}" aria-selected="${id===activeTab}">${label}</button>`).join('');
function lessonCard(l){return `<button class="lesson-card" data-lesson="${escape(l.id)}"><small>RECORDED ACTION / ${escape(l.identity.dll_sha256.slice(0,8))}</small><strong>${escape(titles[l.id]||l.title)}</strong><span>${escape(l.label)} · ${l.duration.toFixed(1)} seconds</span><span>Play gameplay + 3D controls ↗</span></button>`}
$('lessons').innerHTML=lessons.map(lessonCard).join('')||'<p class="empty">No complete, audited action recording is linked yet.</p>';
$('lesson-count').textContent=`${lessons.length} available · ${data.lessons.filter(l=>!l.available).length} awaiting usable recordings`;
$('identity').textContent=`Ledger candidate ${data.coverage.target_identity.dll_sha256} · Generated ${data.generated_utc} · Simulator evidence and physical headset acceptance are separate. No public release is certified.`;
function evidence(row){return row.evidence.map(e=>`<p><a href="${encodeURI(e.url)}" target="_blank">${escape(e.suite)} · ${escape(e.native_status)}</a> · ${e.current?'ledger candidate':'historical build'}${e.reason?'<br>'+escape(e.reason):''}${e.visual_finding?'<br><a href="'+encodeURI(e.visual_review_url)+'" target="_blank">Visual review: '+escape(e.visual_status)+'</a> · '+escape(e.visual_finding):''}</p>`).join('')||'<p>No matching acceptance evidence yet.</p>'}
function linkedLessons(row){return lessons.filter(l=>l.action===actionName(row)||row.evidence?.some(e=>e.case_ids.includes(l.id))).map(l=>`<p><button data-lesson="${escape(l.id)}">Play: ${escape(titles[l.id]||l.title)}</button></p>`).join('')}
function paint(){
 const query=$('search').value.toLowerCase(),filter=$('filter').value;
 let rows=activeTab==='numbers'?data.numbers.literals:activeTab==='settings'?data.numbers.settings:data.coverage.rows.filter(r=>r.kind===activeTab);
 rows=rows.filter(r=>(!query||JSON.stringify(r).toLowerCase().includes(query))&&(!filter||r.status===filter||r.category===filter));
 $('row-count').textContent=`${rows.length} matching entries${rows.length>150?' · first 150 shown; narrow the search for any remaining entry':''}`;
 $('rows').innerHTML=rows.slice(0,150).map(r=>{
  if(activeTab==='numbers')return `<details class="row"><summary><code>${escape(r.file)}:${r.line}</code><strong>${escape(r.literal)}</strong><small>${escape(r.category.replaceAll('_',' '))}</small></summary><div class="body"><pre>${escape(r.context)}</pre><p><a href="${encodeURI(r.source_url)}" target="_blank">Read source at line ${r.line}</a></p><p>Review: ${escape(r.review)}. A literal is not automatically an adjustable setting.</p></div></details>`;
  if(activeTab==='settings')return `<details class="row"><summary><code>${escape(r.unit)}</code><strong>${escape(r.name)}</strong><small>${r.effective_value??'not in installed checker'}</small></summary><div class="body"><p>Default ${r.default} ${escape(r.unit)} · allowed ${r.minimum}–${r.maximum}. Values are source definitions; runtime effects require verification.</p>${r.references.map(x=>`<p><a href="${encodeURI(x.source_url)}" target="_blank"><code>${escape(x.file)}:${x.line}</code></a><pre>${escape(x.context)}</pre></p>`).join('')}</div></details>`;
  const name=actionName(r),binding=r.effective_binding||actions.get(name);
  return `<details class="row"><summary><code>${escape(r.id)}</code><strong>${escape(r.title)}</strong><small>${escape(r.status.replaceAll('_',' '))}</small></summary><div class="body">${r.latest_report?'<p>'+escape(r.latest_report)+'</p>':''}<ul>${(r.acceptance||[]).map(x=>'<li>'+escape(x)+'</li>').join('')}</ul>${binding?'<p>Effective control: <b>'+escape(binding.label||JSON.stringify(binding))+'</b></p>':''}${actions.has(name)?'<button data-control="'+escape(name)+'">Inspect 3D controls</button>':''}${linkedLessons(r)}${evidence(r)}<p>Source: <code>${escape(r.source)}</code></p></div></details>`;
 }).join('');
}
function selectTab(tab){activeTab=tab;$('overview').hidden=tab!=='overview';$('catalog').hidden=tab==='overview';document.querySelectorAll('[data-tab]').forEach(b=>b.setAttribute('aria-selected',String(b.dataset.tab===tab)));$('search').value='';
 $('filter').innerHTML='<option value="">All entries</option>'+(tab==='numbers'?['inline_numeric','named_or_declared','native_contract']:tab==='settings'?[]:['unproven','partial_native_evidence','failure_observed']).map(x=>`<option value="${x}">${x.replaceAll('_',' ')}</option>`).join('');paint();}
document.addEventListener('click',e=>{const tab=e.target.closest('[data-tab]'),l=e.target.closest('[data-lesson]'),view=e.target.closest('[data-view]'),control=e.target.closest('[data-control]');if(tab)selectTab(tab.dataset.tab);if(l)openLesson(l.dataset.lesson);if(view)player?.setView(view.dataset.view);if(control)openControl(control.dataset.control,Number(control.dataset.alternative||0))});
$('search').addEventListener('input',paint);$('filter').addEventListener('change',paint);
function cropVideo(){if(!activeLesson)return;const crop=activeLesson.crop;$('game-frame').style.aspectRatio=`${crop.width}/${crop.height}`;video.style.width=(100*activeLesson.source_width/crop.width)+'%';video.style.height='100%'}
function cueFrame(){if(!activeLesson||!player)return;const t=Math.max(0,video.currentTime-activeLesson.start);const inputs=activeLesson.intervals.filter(i=>i.start<=t&&t<i.end);const missing=player.setInputs(inputs.map(i=>i.input));player.render();$('cue').textContent=inputs.length?inputs.map(i=>i.label).join(' + '):t<activeLesson.duration?'Observe the result':'End of excerpt';$('controller-labels').textContent=inputs.length?inputs.map(i=>i.label).join(' + '):'LEFT CONTROLLER       RIGHT CONTROLLER';$('seek').value=String(Math.min(1,t/activeLesson.duration));$('clock').textContent=`${t.toFixed(1)} / ${activeLesson.duration.toFixed(1)} s`;if(missing.length)$('media-status').textContent='Unmapped 3D control location: '+missing.join(', ');}
function animate(){cueFrame();if(activeLesson&&video.currentTime>=activeLesson.end){video.pause();playing=false;$('play').textContent='Play lesson'}if(activeLesson)frameLoop=requestAnimationFrame(animate)}
async function openLesson(id){
 const selected=lessons.find(l=>l.id===id);if(!selected)return;video.pause();cancelAnimationFrame(frameLoop);activeLesson=selected;playing=false;
 video.hidden=false;$('control-preview').hidden=true;document.querySelector('.playback').hidden=false;
 $('lesson-title').textContent=titles[id]||selected.title;$('instruction').textContent=(descriptions[id]||'{control}').replace('{control}',selected.label.replace(/^(?:HOLD|TAP) /,''));$('play').textContent='Play lesson';$('media-status').textContent='Loading recorded gameplay and controllers…';
 $('lesson-proof').innerHTML=`<p>Recorded action: <b>${escape(selected.native_status)}</b>. Full feature / headset acceptance remains open.</p><p>Build <code>${escape(selected.identity.dll_sha256)}</code><br>Source: ${escape(selected.source_kind)} · ${escape(selected.source_eye)} eye · ${selected.source_dropped_frames} dropped source frames.</p><p>${escape(selected.timing)} ${escape(selected.poses)}</p><p><a href="${encodeURI(selected.run)}" target="_blank">Raw run result</a> · <a href="${encodeURI(selected.media)}" target="_blank">Original source video</a></p><div class="eyes">${selected.eyes.slice(-2).map(e=>`<a href="${encodeURI(e.url)}" target="_blank"><img src="${encodeURI(e.url)}" alt="Final compositor ${escape(e.eye)} eye">${escape(e.eye)} final eye</a>`).join('')}</div>`;
 if(!$('lesson-dialog').open)$('lesson-dialog').showModal();
 try{if(!player){player=new ControllerPlayer($('controller-canvas'),$('detail-canvas'));await player.load()}
  video.src=selected.media;cropVideo();await new Promise((resolve,reject)=>{video.addEventListener('loadedmetadata',resolve,{once:true});video.addEventListener('error',()=>reject(new Error('Source video could not load')),{once:true});video.load()});
  video.currentTime=selected.start;video.playbackRate=Number($('speed').value);player.setView('front');$('media-status').textContent=selected.visual_finding||'Button highlights follow this take. Controller orientation is an instructional view.';frameLoop=requestAnimationFrame(animate);
 }catch(error){$('media-status').textContent=error.message;console.error(error)}
}
async function openControl(name,alternative=0){
 const action=actions.get(name);if(!action)throw Error('Unknown control action');video.pause();cancelAnimationFrame(frameLoop);activeLesson=null;playing=false;video.hidden=true;$('control-preview').hidden=false;document.querySelector('.playback').hidden=true;
 $('lesson-title').textContent=name;$('instruction').textContent='Current binding · rotate and zoom to inspect its physical location.';$('preview-binding').textContent=action.label;$('preview-context').textContent='Used in: '+action.contexts.join(', ');$('cue').textContent=action.label;
 const bindings=action.bindings||[];$('preview-alternatives').innerHTML=bindings.length>1?bindings.map((b,i)=>`<button data-control="${escape(name)}" data-alternative="${i}">Binding ${i+1}: ${escape(b.inputs.join(' + '))}</button>`).join(''):'';
 $('lesson-proof').innerHTML='<p>Illustrative control reference from the effective bindings export. This view does not count as a gameplay test or recorded lesson.</p>';
 if(!$('lesson-dialog').open)$('lesson-dialog').showModal();if(!player){player=new ControllerPlayer($('controller-canvas'),$('detail-canvas'));await player.load()}
 const binding=bindings[alternative],inputs=binding?.inputs||[];const missing=player.setInputs(inputs);player.setView('front');player.render();$('controller-labels').textContent=inputs.join(' + ');
 $('media-status').textContent=missing.length?'Unmapped location: '+missing.join(', '):binding?`${binding.gesture} · ${binding.milliseconds} ms gesture threshold · instructional view`:'This action is unbound.';
 return {name,inputs,missing,alternatives:bindings.length};
}
$('play').onclick=async()=>{if(!activeLesson)return;if(video.paused){if(video.currentTime>=activeLesson.end-.03)video.currentTime=activeLesson.start;try{await video.play();playing=true;$('play').textContent='Pause'}catch(e){$('media-status').textContent=e.message}}else{video.pause();playing=false;$('play').textContent='Play lesson'}};
$('replay').onclick=()=>{if(activeLesson){video.currentTime=activeLesson.start;video.play().catch(e=>$('media-status').textContent=e.message);$('play').textContent='Pause'}};
$('seek').oninput=()=>{if(activeLesson){video.currentTime=activeLesson.start+Number($('seek').value)*activeLesson.duration;cueFrame()}};
$('speed').onchange=()=>video.playbackRate=Number($('speed').value);
function close(){video.pause();activeLesson=null;cancelAnimationFrame(frameLoop);$('lesson-dialog').close()}
$('close-lesson').onclick=close;$('lesson-dialog').addEventListener('cancel',close);window.addEventListener('resize',()=>{cropVideo();player?.render()});
window.fieldKit={openLesson,openControl,selectTab,renderControls:(inputs,azimuth=0)=>{if(!player?.ready)throw Error('Controllers not loaded');cancelAnimationFrame(frameLoop);video.pause();player.setInputs(inputs);player.azimuth=azimuth;return player.capture()},seek:async seconds=>{if(!activeLesson)throw Error('No lesson selected');video.pause();const target=activeLesson.start+Math.max(0,Math.min(seconds,activeLesson.duration));if(Math.abs(video.currentTime-target)>.00001||video.seeking)await new Promise((resolve,reject)=>{const timer=setTimeout(()=>{video.removeEventListener('seeked',done);reject(Error('Video seek timed out'))},5000);function done(){clearTimeout(timer);resolve()}video.addEventListener('seeked',done,{once:true});video.currentTime=target});cueFrame();return {time:video.currentTime,controls:player.active}},get ready(){return !!player?.ready},get lesson(){return activeLesson},get mappedInputs(){return player?.active}};
selectTab('overview');
